version: '3.7'

services:
  bdmariadb1:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
